SELECT  VISITED_ON, 
        (SELECT SUM(AMOUNT)
        FROM CUSTOMER
        WHERE VISITED_ON BETWEEN DATE_SUB(C.VISITED_ON, INTERVAL 6 DAY) AND C.VISITED_ON) AS AMOUNT, 
        (SELECT ROUND(SUM(AMOUNT)/7,2)
        FROM CUSTOMER
        WHERE VISITED_ON BETWEEN DATE_SUB(C.VISITED_ON, INTERVAL 6 DAY) AND C.VISITED_ON) AS AVERAGE_AMOUNT

FROM CUSTOMER C 
WHERE VISITED_ON >= 
(SELECT DATE_ADD(MIN(VISITED_ON), INTERVAL 6 DAY) AS    VISITED_ON
FROM CUSTOMER 
) 
GROUP BY VISITED_ON
